### ISSUE TITLE
Update Figure 1 with geohack

### ISSUE THREAD

**Issue by aaarendt** [uwescience/HackWeek-Writeup#30]
@jakevdp @arokem do one of you have HackSpectrum.png as a vector graphic so I can add Geohack on the plot? Otherwise I'll edit manually somehow. Thanks

**Comment by arokem** [comment]
I do not. Looks like @jakevdp added it in https://github.com/uwescience/HackWeek-Writeup/commit/0d7cf54d73a26432b51dc4206ecf21eab6d884ae

**Comment by jakevdp** [comment]
I shared the google draw source with both of you

**Comment by jakevdp** [comment]
Also, I'm not married to the figure in its current form... I think it might be useful to put some more thought into it

**Comment by dhuppenkothen** [comment]
Can we close this? I think we merged the figure with geohack in it, right?

**Comment by arokem** [comment]
yep. in #33. closing
