### ISSUE TITLE
discussion on the role of junior versus senior reserachers

### ISSUE THREAD

**Issue by aaarendt** [uwescience/HackWeek-Writeup#31]
https://github.com/uwescience/HackWeek-Writeup/pull/28/commits/a0532647070f75f4707d4a01d6a2ec6ab3b00054#diff-fb6416b20e925ad59e9f77c28b957d88R90

`Firstly, because junior researchers are often more up-to-date on the latest technologies and methods, the focus on computational aspects implies that unlike at a summer school, junior participants are often more knowledgable about these topics than their more senior counterparts. Therefore, the seniority of researchers conducting hack week tutorials or who are generally brought in as experts skews younger than they would in a traditional summer school.`

I thing this is true in some cases, but I would caution against these broad generalizations. I know of many cases where young scientists just have not been working in open source software long enough and don't know what's out there. And I know a lot of more senior researchers who have pioneered the new stuff more than anybody. Furthermore, I see length of time in any given field imparts wisdom about how all the pieces fit together and should be seen as a positive quality. So while it may be true that tutors skew younger than in a summer school, we might question if that is desirable. It reads right now as if we think that to be the case, but I would challenge that a bit. Or I would at least ask why we think this is an important point to highlight?

**Comment by dhuppenkothen** [comment]
I will see whether this requires more reformulating.

**Comment by aaarendt** [comment]
I'm happy to close this?

**Comment by arokem** [comment]
+1 for closing.
