### ISSUE TITLE
license correct?

### ISSUE THREAD

**Issue by davidwhogg** [uwescience/HackWeek-Writeup#6]
I think we should be CC-BY-ND ; are we? @jakevdp you are on the hot seat

**Comment by davidwhogg** [comment]
Oh, maybe there IS no BY-ND, since ND implies BY?

**Comment by jakevdp** [comment]
I thought I got the one you mentioned. Is there another license you had in mind?

**Comment by jakevdp** [comment]
Are you thinking of this one? https://creativecommons.org/licenses/by-nd/4.0/legalcode

**Comment by jakevdp** [comment]
Fixed in 3d51dfc52e5e79232790563264023ca305677cdc

**Comment by davidwhogg** [comment]
thanks!
